// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "WebCade-iOS",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "WebCade-iOS",
            targets: ["AppModule"],
            teamIdentifier: "AKFG84X65H",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .gamepad),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .games
        )
    ],
    dependencies: [
        .package(url: "https://github.com/httpswift/swifter.git", "1.5.0"..<"2.0.0"),
        .package(url: "https://github.com/scinfu/SwiftSoup.git", "2.13.5"..<"3.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "Swifter", package: "swifter"),
                .product(name: "SwiftSoup", package: "SwiftSoup")
            ],
            path: ".",
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)